name: Deploy Python Script

on:
  push:
    branches:
      - main   # Trigger deploy when pushing to the 'main' branch (adjust to your branch name)

jobs:
  deploy:
    runs-on: debian-latest  # Runs on an Ubuntu VM for GitHub Actions

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2   # Check out your code from the GitHub repo

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Adjust Python version if needed

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install Python dependencies from requirements.txt

    - name: Deploy Python Script to Vultr (or remote server)
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa  # Add the private key from GitHub Secrets
        chmod 600 ~/.ssh/id_rsa  # Set appropriate permissions for the private key
        ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts  # Add the server to known hosts

        # SSH into the server and deploy the code
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          # Navigate to the script directory
          cd /path/to/your/script/directory || exit

          # Pull the latest code (optional)
          git pull origin main || exit

          # Install/update the dependencies
          pip3 install -r requirements.txt || exit

          # Run your Python script (adjust to your script name)
          python3 your_script.py || exit
        EOF
      env:
        SSH_USER: ${{ secrets.SSH_USER }}      # The SSH user for your server
        SSH_HOST: ${{ secrets.SSH_HOST }}      # The IP address or hostname of your server
